### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by corradomatt** [Rarst/meadow#2]
Hi @Rarst - this project looks very interesting and it might be something I want to implement within my projects. I noticed the experiment disclaimer on the project readme and was wondering if you've been using this in production? It seems that since you started this a year ago and you're using this in production regularly, maybe it is battle tested enough to remove that disclaimer?

Just curios and thanks for sharing!!

**Comment by Rarst** [comment]
I have used Meadow (Hybrid Wing parent + private child theme) for my own site Rarst.net in production since last autumn. I know it has been used some outside of that in private projects by other people, but I hadn't that much feedback about those. I suppose if it had exploded in their faces I would have. :)

At the moment my concern isn't as much _stability_. I had zilch stability issues, it just works — Twig is insanely battle tested and glue for WP parts isn't that elaborate.

My concerns about proceeding to declaring it stable are more about APIs and general direction. I'd like to explore more of DSL elements, but working with parsing doesn't come easily to me so it is a little stale at the moment.

As of right now I would say:

 - if what Meadow offers and explores just _makes sense_ to you, then you can surely take a stab at making use of it
 - if you are interested in Twig _in general_ and don't care that much about specific implementation, but rather history of production use I'd say consider Timber instead

**Comment by corradomatt** [comment]
Thanks for the feedback! I'm going to play with Timber a bit as well.....but I really like your structure here. I'm trying to implement a more MVC pattern approach with WP plugins to include the use of autoloaders namespacing and dependency injectors (specifically https://r.je/dice.html). Your theme inspires me to make use of composer more as well.

Thanks again!

**Comment by Giuseppe-Mazzapica** [comment]
I built a site with Meadow, it is in production and online. As I signed a *non-disclosure* agreement with client regarding techonlogies used so I can't link it. Not sure if that is actually against the agreement, but no will to read the contract now, so better be sure :)

I can say it's a website for a bank (nothing security relevant there) and according to last data I have, it has a non-trivial amount of daily visitors and it works with no problems. Client is fain as well.

So, yes, I can say Meadow is procution ready.

Personally, I prefer Meadow over Timber because I don't like framework, as I prefer to choose myself my architecture, so a library is preferable over a framework for me.

Regarding the usage of Twig in WordPress, it can be a bit frustrating sometimes, because of the huge number of global variables. Reason is in Twig you can't just type `global $wp;` (or whatever), and sometimes it make things a bit harder.

Since I released Foil, honestly, I've not used Meadow anymore, but I can say without doubt that IMO is the best (surely the easiest and the less opinionated) Twig implementation for WordPress.

If I have to find a flaw is that documentation for custom node is a bit shallow, but @Rarst was very helpful in loopchat when I found myself lost :)
